### ISSUE TITLE
[RFC] ROS2 Gem - Multiplayer support

### ISSUE THREAD

**Issue by lgleim** [o3de/sig-simulation#73]
### Summary

Add support for multiplayer (client/server) simulation to the ROS2 Gem, based on a (Gazebo-inspired) "fat-client" architecture, using an O3DE server for state synchronization among clients.

### What is the relevance of this feature?

There are an increasing number of use cases for simulating fleets of robots. 

One area of application is in the context of warehouse simulation (cf. the [Ros2FleetRobotTemplate](https://github.com/o3de/o3de-extras/tree/development/Templates/Ros2FleetRobotTemplate)) where many AMRs need to be simulated in the same environment.

While O3DE is already capable of simulating the physics of many robots (100+) on a single machine, there are clear limits to single-node scalability. This work should raise that ceiling and explore the scalability of an architecture with centralized state synchronization.

### Feature design description

To evaluate the feasibility and scalability properties of multi-robot simulation in O3DE using a traditional Client-Server architecture, support for the O3DE Multiplayer Gem should be added to the ROS2 Gem.
Developers will then be able to simulate different robots on different machines, while the simulation state will be synchronized through a central game server. This approach is analogous to traditional multiplayer gaming.

Loosely inspired by the architecture of Gazebo Ignition, which employs a central "primary" for synchronizing the state of the simulation, we plan to make use of the O3DE Multiplayer Gem, creating
 - A single, central simulation Server: Responsible for state synchronization (transforms, physics-state) and not simulating any ROS2-specific components (as far as possible)
 - One Client per robot: All "heavy" components (e.g. rendering of camera sensors / LIDARs, control, ROS communication) are handled exclusively by one client, which is realized through the "Autonomous" role

### Technical design description

- [ ] Add a Utility function that allows ROS2 Components to determine if they are running in a multiplayer environment & if yes, on an autonomous entity to adapt their behavior accordingly
- [ ] Adapt ROS2 Components such that they are only activated on Clients with "Autonomous" role
- [ ] Adapt ROS2SystemComponent such that each client has a distinct ROS2 node name
- [ ] Adapt ROS2SpawnerComponent such that the assigned namespaces do not clash, e.g. using random namespace suffixes
- [ ] Create custom NetworkTransform & NetworkRigidBody Components that support Client-authoritative Autonomous2Authority Synchronization, such that the ROS2 Controller Components do not need to be adapted

### What are the advantages of the feature?

- Increased scalability of Robotics Simulation with O3DE
- An additional example of developing "multiplayer" applications with O3DE

### What are the disadvantages of the feature?

- Increased complexity of the ROS2 Gem codebase 
- Likely additional Editor Components for the users to configure 

### How will this be implemented or integrated into the O3DE environment?

- This change would introduce the Multiplayer Gem as an additional build dependency to the ROS2 Gem
- Users should not Explain how a developer will integrate this into the codebase of O3DE and provide any specific library or technical stack requirements.

### Are there any alternatives to this feature?

- Reducing simulation complexity to improve single-node performance

### How will users learn this feature?

- A multiplayer version of the ROS2FleetTemplate should be created
- A tutorial for setting up multiplayer support for a ROS2 O3DE Simulation should be provided
- Documentation should be augmented for any behavioral changes / additional setup & configuration steps

**Comment by adamdbrw** [comment]
@lgleim could you update the status of this RFC?

**Comment by lgleim** [comment]
This work is on hold for now but may be resumed at a later point
